### ISSUE TITLE
Balance load in Public Cloud in GCP

### ISSUE THREAD

**Issue by sujal-garg** [Developer-Student-Clubs-MMDU/Cloud-Computing#5]

**Comment by ShivamKr9304** [comment]
what topic should be covered in documentation 
&
In which type of file type is acceptable 
In MS Word

**Comment by Manishgupta200** [comment]
Assign it to me

**Comment by harshrj9939** [comment]
Please assign this to me

**Comment by Manishgupta200** [comment]
Hey @harshrj9939. I assigned it to you. Work on it.

**Comment by Nishchaybhuker20** [comment]
Plz assign this to me.
